### ISSUE TITLE
Can not find ConfigSourceHandler

### ISSUE THREAD

**Issue by zhangbingxiao** [foldright/auto-pipeline#115]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/61449488/199672973-7901b42d-cf26-4c05-9ff8-ff2fe3639a09.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/61449488/199673000-839dea2c-7d15-467d-bb4b-1b819828fa92.png">
why?

**Comment by zavakid** [comment]
@zhangbingxiao 
do you enable the IDE annotation process? like below:

<img width="950" alt="image" src="https://user-images.githubusercontent.com/693320/200173456-65a9beb5-0723-4f8d-87e4-dfaf9b632744.png">

**Comment by zhangbingxiao** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/61449488/200255536-76a64beb-64f9-4773-abc3-540e7d77697a.png">
打开后还是不行，不知道为什么，我看ConfigSourceHandler这个类并没有在项目中存在，为什么能够实现它呢？

**Comment by zavakid** [comment]
@zhangbingxiao `ConfigSourceHandler` 是通过 annotation processor 生成的，因此是可以编译通过的，应该是第一次打开 IDE 时出现的问题。

是第一次打开 auto-pipeline 这个工程然后找不到这些类的吗？你能描述一下你是如何出现这个问题的吗？我看看本地如何复现

**Comment by zavakid** [comment]
@zhangbingxiao 我想我已经复现出来了。 原因很可能是第一次打开 auto-pipeline 工程时，还没有生成的类文件，解决比较明确：先执行  `mvn clean install`， 再用 IDE 打开工程。我已经复现并且也已经解决了，你看看能否解决？

**Comment by zavakid** [comment]
@zhangbingxiao 现在已经可以直接安装插件，帮忙解决这个问题了，见这里： https://plugins.jetbrains.com/plugin/20535-auto-pipeline
